name: Build the code
on:
 push:
  branches:
   - master
jobs:
 build-job:
  runs-on: ubuntu-latest
  steps:
   - name: Clone the code 
     uses: actions/checkout@v3 
   - name: install dependencies
     run: npm ci
   - name: Test the code
     id: test-step
     run: npm run test
   - name: Upload the test report on github 
     if: failure() && steps.test-step.outcome='failure'
     uses: actions/upload-artifact@v4
     with:
       name: mytestreport
       path: test.json
