name: Test the code and fetch the test report
on:
 push:
  branches:
   - master
jobs:
 build-job:
  runs-on: ubuntu-latest
  steps:
   - name: Clone the code 
     uses: actions/checkout@v3 
   - name: install dependencies
     run: npm ci
   - name: Test the code
     run: npm run test
