name: Build the code
on:
 push:
  branches:
   - master
jobs:
 build-job:
  runs-on: ubuntu-latest
  steps:
   - name: Clone the code 
     uses: actions/checkout@v3 
   - name: install dependencies
     run: npm ci
   - name: Test the code
     run: npm run test
   - name: Upload the test report on github 
     uses: actions/upload-artifact@v4
     with:
       name: mytestreport
       path: test.json
   - name: Build the code 
     run: npm run build 
   - name: Upload the build artifacts on github 
     uses: actions/upload-artifact@v4
     with:
      name: mybuild
      path: dist
 deployJob:
  needs: build-job
  runs-on: ubuntu-latest
  steps:
   - name: Get build artifacts from previous job 
     uses: actions/download-artifact@v4
     with:
      name: mybuild
   - name: output contents
     run: ls
   - name: Deploy code 
     run: echo 'deploying....'
